create table if not exists public.admins (
  id bigint generated by default as identity primary key,
  username text not null unique,
  password text not null,
  full_name text default 'System Admin',
  role text default 'admin',
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- RLS Politikaları (opsiyonel, şimdilik herkese açık okuma verelim admin paneli olduğu için client-side auth yapıyoruz)
alter table public.admins enable row level security;

create policy "Admins can read their own data"
on public.admins for select
using (true); -- Şimdilik login için genel okuma izni, production'da daraltılmalı

-- İlk admin kullanıcısını ekle
insert into public.admins (username, password, full_name)
values ('digivisor', 'Digivisor@2025?*', 'Digivisor Admin')
on conflict (username) do nothing;
